# PhysMaster Configs

llm:
  base_url: "https://api.gpugeek.com/v1"
  api_key: "u0rgjezq53e5tv01000dg95v0yqn2eecv02b7z3r"
  model: "Vendor2/GPT-5.4"

# Basics
pipeline:
  query_file: "instructions/test.txt"
  output_path: "outputs"
  parallel_processes: 2
  max_rounds: 10

mcts:
  draft_expansion: 2
  revise_expansion: 1
  exploration_constant: 1.414
  active_beam_width: 3

# Clarifier settings
clarifier:
  max_key_concpets: 5

skills:
  enabled: true
  roots:
    - "LANDAU/skills"

# LANDAU settings
landau:
  library_enabled: true
  library: "LANDAU/library"
  
  workflow_enabled: false
  workflow: "LANDAU/workflow/cs_kernel.yaml"

  prior_enabled: true
  prior: "LANDAU/prior"

  wisdom_save_enabled: false

visualization:
  enabled: true
