# PhysMaster Configs

# Basics
pipeline:
  query_file: "instructions/test.txt"
  output_path: "outputs"
  parallel_processes: 3
  max_rounds: 3

mcts:
  draft_expansion: 2
  revise_expansion: 1
  exploration_constant: 1.414
  active_beam_width: 3

# Clarifier settings
clarifier:
  max_key_concpets: 5

# LANDAU settings
landau:
  library_enabled: true
  library: "LANDAU/library"
  
  workflow_enabled: true
  workflow: "LANDAU/workflow"
  
  techniques_enabled: true
  techniques: "LANDAU/techniques"

  prior_enabled: true
  prior: "LANDAU/prior"

visualization:
  enabled: true
