# Physics Master Configuration

# Clarifier settings
clarifier:
  query_file: "instructions/test.txt"
  schema_file_path: "agent/clarifier/schema"
  output_path: "outputs"
  max_key_concpets: 5

# Knowledge Base settings
knowledge_base:
  enabled: false
  local_root: "knowledge_base/local_knowledge_base"
  global_root: "knowledge_base/global_knowledge_base"

  cleanup_parax_librarian: true
  write_local_to_global: true
  cleanup_local_after_run: true

  pasax:
    root_path: "agent/librarian/Pasa-X-papermaster_new"

  global:
    enabled: true  

pipeline:
  parallel_processes: 2
  max_nodes: 4
  complete_score_threshold: 0.7

mcts:
  draft_expansion: 2
  revise_expansion: 2
  improve_expansion: 1
  exploration_constant: 1.414

visualization:
  enabled: true
